[type.map]
extend-glob = ["*.map"]
check-file = false

[type.html]
extend-glob = ["*.html"]
check-file = false

[type.ini]
extend-glob = ["languages/*.ini"]
check-file = false

[default.extend-words]
ba = "ba"
fof="fof"
datas =     "datas"
cose="cose"
fo="fo"

[files]
extend-exclude = ["languages/*.ini", "languages/*.po"]